name:                EchoBot
version:             0.1.0.0
github:              "GooseDB/EchoBot"
license:             BSD3
author:              "GooseDB"
maintainer:          "GooseDB@yandex.com"

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- req
- aeson


executables:
  EchoBot-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  EchoBot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
